# Reference: <https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions>


name: Build application

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.1.0 # https://github.com/marketplace/actions/checkout
      - name: Cache build
        uses: actions/cache@v1.1.2  # https://github.com/marketplace/actions/cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package.json') }}
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Build app
        run: npm run build
      - name: Deploy Github Pages
        uses: crazy-max/ghaction-github-pages@v1.4.0  # https://github.com/marketplace/actions/github-pages
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token automatically generated for workflow