# Reference: <https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions>

name: Build application

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Test
        run: echo Test